# Generated by Django 6.0.1 on 2026-01-29 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='series_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studygroups',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to='core.users'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.studygroups', verbose_name='Группа'),
        ),
    ]
