# Generated by Django 5.2.11 on 2026-02-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], default='pending', max_length=10),
        ),
    ]
