# Generated by Django 5.2.11 on 2026-02-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_connectionrequest_status'),
        ('core', '0002_alter_lessons_subject'),
    ]

    operations = [
    ]
