# Generated by Django 6.0.1 on 2026-01-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessons_price_studenttariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttariff',
            old_name='hourly_rate',
            new_name='price',
        ),
        migrations.AddField(
            model_name='studenttariff',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.studygroups'),
        ),
        migrations.AlterField(
            model_name='studenttariff',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
    ]
