# Generated by Django 6.0.1 on 2026-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_hourly_rate_studenttariff_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonattendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='lessonattendance',
            name='status',
        ),
    ]
