# Generated by Django 6.0.1 on 2026-01-30 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_users_balance_alter_lessonattendance_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lessonattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.users')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
