# Generated by Django 6.0.1 on 2026-01-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_delete_transactions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='student_transactions',
        ),
    ]
