# Generated by Django 6.0.1 on 2026-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transaction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonattendance',
            name='was_present',
            field=models.BooleanField(default=True),
        ),
    ]
