# Generated by Django 6.0.1 on 2026-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lessonattendance_was_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattendance',
            name='was_present',
            field=models.BooleanField(default=False),
        ),
    ]
