# Generated by Django 6.0.1 on 2026-01-31 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lessonattendance_was_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileslibrary',
            name='file_path',
        ),
        migrations.AddField(
            model_name='fileslibrary',
            name='file',
            field=models.FileField(default='', upload_to='tutor_materials/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileslibrary',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.users'),
        ),
        migrations.AlterField(
            model_name='fileslibrary',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
