# Generated by Django 6.0.1 on 2026-01-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_fileslibrary_file_path_fileslibrary_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileslibrary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tutor_materials/%Y/%m/%d/'),
        ),
    ]
