# Generated by Django 6.0.1 on 2026-01-31 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fileslibrary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='lessons_materials', to='core.fileslibrary'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Задано'), ('submitted', 'На проверке'), ('completed', 'Выполнено')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, related_name='homework_files', to='core.fileslibrary')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework', to='core.users')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subjects')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to='core.users')),
            ],
            options={
                'db_table': 'homework',
                'ordering': ['-created_at'],
            },
        ),
    ]
