# Generated by Django 6.0.1 on 2026-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lessons_materials_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
    ]
