# Generated by Django 5.2.10 on 2026-02-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homeworkresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Telegram'),
        ),
    ]
