# Generated by Django 5.2.11 on 2026-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_users_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
