# Generated by Django 5.2.11 on 2026-02-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lessons_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.users'),
            preserve_default=False,
        ),
    ]
