# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_check_constraints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorSubjects',
        ),
    ]
