# Generated by Django 5.2.11 on 2026-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_users_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя Отчество родителя'),
        ),
        migrations.AddField(
            model_name='users',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакты родителя'),
        ),
        migrations.AddField(
            model_name='users',
            name='school_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс'),
        ),
    ]
