# Generated by Django 5.2.11 on 2026-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_users_parent_name_users_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='tutor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий репетитора'),
        ),
    ]
