# Generated by Django 5.2.11 on 2026-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_homework_tutor_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('pending', 'Задано'), ('submitted', 'На проверке'), ('revision', 'Доработать'), ('completed', 'Выполнено')], default='pending', max_length=15),
        ),
    ]
