# Generated by Django 5.2.11 on 2026-02-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_homework_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorStudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about_me', to='core.users')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_created', to='core.users')),
            ],
            options={
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
